# Generated by Django 3.0.3 on 2020-05-23 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWorks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=10)),
                ('workid', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=500)),
                ('plannedtime', models.IntegerField(default=0)),
                ('planneddate', models.DateField()),
                ('actualtime', models.IntegerField(default=0)),
                ('actualdate', models.DateField()),
                ('remark', models.CharField(max_length=500)),
                ('iscomplete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=10)),
                ('workid', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=10)),
                ('workid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empid', models.CharField(max_length=10)),
                ('workid', models.CharField(max_length=10)),
                ('workordertype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('iscomplete', models.IntegerField(default=0)),
                ('workordernumber', models.IntegerField(default=0)),
                ('productname', models.CharField(max_length=100)),
                ('expecteddate', models.DateField()),
                ('woissuedate', models.DateField()),
                ('acceptedby', models.CharField(max_length=100)),
                ('customername', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('attachments', models.CharField(max_length=100)),
                ('customercontact', models.CharField(max_length=10)),
                ('cusromeremail', models.CharField(max_length=100)),
                ('amountspent', models.IntegerField(default=0)),
                ('isdone', models.IntegerField(default=0)),
            ],
        ),
    ]
