# Generated by Django 3.0.3 on 2020-05-26 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kathi', '0002_assignedworks_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedworks',
            name='planneddate',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
