# Generated by Django 3.0.3 on 2020-05-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kathi', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='expirience',
            new_name='experience',
        ),
    ]
