# Generated by Django 3.0.3 on 2020-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kathi', '0005_auto_20200528_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
