# Generated by Django 3.0.3 on 2020-06-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kathi', '0007_auto_20200623_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedWorks',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pic',
        ),
    ]
