# Generated by Django 3.0.3 on 2020-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kathi', '0009_auto_20200623_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='CompletedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
